-   id: clabs-smart-commit
    name: CustomerLabs smart commit hook
    description: Automatically transform your Git commit messages into Jira smart commits
    entry: clabs-smart-commit
    language: python
    stages: [prepare-commit-msg]
    always_run: true